
services:
  - type: web
    name: shopee-backend
    runtime: go
    buildCommand: go build -o app main.go
    startCommand: ./app
    rootDir: backend
    autoDeploy: true
    plan: free
    envVars:
      - key: PORT
        value: 8080

  - type: web
    name: shopee-frontend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    rootDir: frontend
    autoDeploy: true
    plan: free
